-- *  CommonHash
-- 
-- 
-- // ??? ?????? ???? ????? ??????, ?? ?????
-- function NumberAdd takes integer Playerid, integer Unitid returns nothing
--     local integer Cunit = LoadInteger(CommonHash,Playerid, Unitid) + 1
--     call SaveInteger(CommonHash,Playerid,Unitid,Cunit)
-- endfunction
-- 
-- function NumberRem takes integer Playerid, integer Unitid returns nothing
--     local integer Cunit = LoadInteger(CommonHash,Playerid, Unitid) - 1
--     call SaveInteger(CommonHash,Playerid,Unitid,Cunit)
-- endfunction
-- 
-- 
-- 
-- ***************************************************************************
