-- Auto-generated manifest for 80_generated_runtime split
-- Source: 80_generated_runtime.lua

"00_header.lua"  -- 00_header  (11 lines)
"10_globals.lua"  -- Global Variables  (730 lines)
"20_custom_script.lua"  -- Custom Script Code  (246 lines)
"30_player_counter.lua"  -- Counter  (13 lines)
"40_bool_exprs.lua"  -- gGlobal objects  (53 lines)
"50_lib_new_functions.lua"  -- LibNewFunctions  (76 lines)
"51_update_graph.lua"  -- UpdateGraph  (47 lines)
"52_enter.lua"  -- Enter  (19 lines)
"53_income_settings.lua"  -- Settings  (21 lines)
"54_count_dis.lua"  -- CountAddDis and CountDelDis  (205 lines)
"55_clear_ec.lua"  -- ClearEc  (16 lines)
"56_clear_player.lua"  -- ClearPlayer  (49 lines)
"57_timed_update.lua"  -- TimedUpdate  (98 lines)
"58_init_things.lua"  -- InitThings  (18 lines)
"59_ui_setup.lua"  -- PlayerUI  (161 lines)
"60_income_tooltip.lua"  -- IncomeTooltip  (39 lines)
"61_all_players.lua"  -- AllPlayersStart  (32 lines)
"62_common_hash.lua"  -- CommonHash  (17 lines)
"63_clear_allies.lua"  -- ClearAllies  (13 lines)
"64_del_unit.lua"  -- DelUnitStart  (7 lines)
"65_random_locs.lua"  -- RandomLocationFromUnits  (2 lines)
"66_race_circles.lua"  -- CreateRaceCircles  (11 lines)
"67_city_check.lua"  -- CityCountCheck  (43 lines)
"68_subgroup2.lua"  -- SubGroup2  (21 lines)
"70_race_farm_start.lua"  -- Pstart  (11 lines)
"71_tier_system.lua"  -- CountForTier  (36 lines)
"72_farm_limit.lua"  -- ChangeSpellLimit  (30 lines)
"73_horde_w2.lua"  -- HordeW2On  (24 lines)
"74_w2_xp.lua"  -- XpLevelW2  (48 lines)
"75_cult_on.lua"  -- CultOn  (24 lines)
"76_forest_trolls.lua"  -- StartForestTrolls  (16 lines)
"77_jungle_trolls.lua"  -- StartJungleTrolls  (32 lines)
"78_forsaken_on.lua"  -- ForsacenOn  (32 lines)
"79_building_tier.lua"  -- BuildingTierSystem  (19 lines)
"80_dragons_on.lua"  -- DragonsOn2  (11 lines)
"81_elem_on.lua"  -- ElemOn  (9 lines)
"82_ai_points.lua"  -- PointAi  (42 lines)
"83_turn_off_ai.lua"  -- TurnOffAi  (2 lines)
"84_globals_start.lua"  -- Globals And Start setttings  (3 lines)
"85_lib_ai_stuff.lua"  -- LibDifferentAiStuff  (2 lines)
"86_lib_races.lua"  -- LibRaces  (2 lines)
"90_continental_bool.lua"  -- ContinentalBoolexrs  (112 lines)
"91_continental_templates.lua"  -- ContinentalTemplates  (29 lines)
"92_dungeons.lua"  -- Dungeons  (144 lines)
"93_continental_main.lua"  -- ContinentalMain  (198 lines)
"94_ai_attack.lua"  -- TryToAttack2 Uni  (321 lines)
"95_ai_attack_naval.lua"  -- TryToAttackN Uni  (82 lines)
"96_ai_killed_city.lua"  -- KilledCity  (8 lines)
"97_ai_water.lua"  -- GoToWater  (63 lines)
"98_ai_build.lua"  -- TryToBuild  (72 lines)
"99_ai_unit_joins.lua"  -- AiUnitJoins  (15 lines)
"100_ai_capital.lua"  -- CapitalEnter  (17 lines)
"105_emerald_dream.lua"  -- EnterGreen2  (72 lines)
"110_item_drops.lua"  -- Unit Item Tables  (40 lines)
"115_sounds.lua"  -- Sound Assets  (25 lines)
"120_unit_creation.lua"  -- Unit Creation  (943 lines)
"130_regions.lua"  -- Regions  (166 lines)
"135_cameras.lua"  -- Cameras  (107 lines)
"140_triggers.lua"  -- Triggers  (42490 lines)
