from __future__ import annotations

import argparse
from pathlib import Path


MODULE_ORDER = [
    "globals.lua",
    "tables.lua",
    "utils.lua",
    "debug_probe.lua",
    "init.lua",
    "economy.lua",
    "stolica.lua",
    "ai_filters.lua",
    "ai_utils.lua",
    "spells_common.lua",
    "race_init.lua",
    "spells_races_1.lua",
    "spells_races_2.lua",
    "lobby.lua",
    "main.lua",
]

DEBUG_START_MARKER = 'do; local _, codeLoc = pcall(error, "", 2)'
DEBUG_END_MARKER = "if Debug and Debug.endFile then Debug.endFile() end"


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8-sig")


def write_text(path: Path, text: str) -> None:
    path.write_text(text, encoding="utf-8", newline="\n")


def extract_debug_utils(debug_map_script: Path) -> str:
    text = read_text(debug_map_script)
    start = text.find(DEBUG_START_MARKER)
    if start == -1:
        raise RuntimeError(f"Could not find Debug Utils start marker in {debug_map_script}")

    end = text.find(DEBUG_END_MARKER, start)
    if end == -1:
        raise RuntimeError(f"Could not find Debug Utils end marker in {debug_map_script}")

    end += len(DEBUG_END_MARKER)
    debug_text = text[start:end]

    replacements = {
        "ALLOW_INGAME_CODE_EXECUTION = true": "ALLOW_INGAME_CODE_EXECUTION = false",
        "USE_NAME_CACHE = true": "USE_NAME_CACHE = false",
        "AUTO_REGISTER_NEW_NAMES = true": "AUTO_REGISTER_NEW_NAMES = false",
        "NAME_CACHE_DEPTH = 4": "NAME_CACHE_DEPTH = 0",
        "EXCLUDE_BJ_GLOBALS_FROM_NIL_WARNINGS = false": "EXCLUDE_BJ_GLOBALS_FROM_NIL_WARNINGS = true",
    }
    for before, after in replacements.items():
        debug_text = debug_text.replace(before, after)

    return debug_text


def build_script(modules_dir: Path, debug_map_script: Path | None) -> str:
    parts: list[str] = []
    parts.append("-- Auto-generated by lua_rewrite/build_lua_map.py")
    parts.append("-- Source of truth: module files inside map_lua.w3m")
    parts.append("-- Do not hand-edit this file; rebuild it instead.")
    parts.append("")

    if debug_map_script is not None:
        parts.append("-- Debug Utils extracted from LuaDebugUtils_v2.5b.w3m")
        parts.append(extract_debug_utils(debug_map_script).rstrip())
        parts.append("")

    for module_name in MODULE_ORDER:
        module_path = modules_dir / module_name
        if not module_path.is_file():
            raise RuntimeError(f"Missing module: {module_path}")

        parts.append(f"-- >>> BEGIN {module_name}")
        parts.append(read_text(module_path).rstrip())
        parts.append(f"-- <<< END {module_name}")
        parts.append("")

    return "\n".join(parts).rstrip() + "\n"


def main() -> int:
    root = Path(__file__).resolve().parent
    default_modules_dir = root / "map_lua.w3m"
    default_output = root / "war3map.probe.generated.lua"
    default_debug_map = root.parent.parent / "LuaDebugUtils_v2.5b.w3m" / "war3map.lua"

    parser = argparse.ArgumentParser(description="Build war3map.lua from module files.")
    parser.add_argument("--modules-dir", type=Path, default=default_modules_dir)
    parser.add_argument("--output", type=Path, default=default_output)
    parser.add_argument("--debug-map-script", type=Path, default=default_debug_map)
    parser.add_argument("--no-debug-utils", action="store_true")
    args = parser.parse_args()

    debug_map_script = None if args.no_debug_utils else args.debug_map_script
    output = build_script(args.modules_dir, debug_map_script)
    write_text(args.output, output)

    print(f"Built {args.output}")
    if debug_map_script is None:
        print("Debug Utils: disabled")
    else:
        print(f"Debug Utils source: {debug_map_script}")
    print(f"Modules dir: {args.modules_dir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
