function InitCustomPlayerSlots()
    -- Player 0
    SetPlayerStartLocation(Player(0), 0)
    SetPlayerColor(Player(0), ConvertPlayerColor(0))
    SetPlayerRacePreference(Player(0), RACE_PREF_HUMAN)
    SetPlayerRaceSelectable(Player(0), false)
    SetPlayerController(Player(0), MAP_CONTROL_USER)
    -- Player 1
    SetPlayerStartLocation(Player(1), 1)
    ForcePlayerStartLocation(Player(1), 1)
    SetPlayerColor(Player(1), ConvertPlayerColor(1))
    SetPlayerRacePreference(Player(1), RACE_PREF_HUMAN)
    SetPlayerRaceSelectable(Player(1), false)
    SetPlayerController(Player(1), MAP_CONTROL_USER)
    -- Player 2
    SetPlayerStartLocation(Player(2), 2)
    ForcePlayerStartLocation(Player(2), 2)
    SetPlayerColor(Player(2), ConvertPlayerColor(2))
    SetPlayerRacePreference(Player(2), RACE_PREF_HUMAN)
    SetPlayerRaceSelectable(Player(2), false)
    SetPlayerController(Player(2), MAP_CONTROL_USER)
    -- Player 3
    SetPlayerStartLocation(Player(3), 3)
    ForcePlayerStartLocation(Player(3), 3)
    SetPlayerColor(Player(3), ConvertPlayerColor(3))
    SetPlayerRacePreference(Player(3), RACE_PREF_HUMAN)
    SetPlayerRaceSelectable(Player(3), false)
    SetPlayerController(Player(3), MAP_CONTROL_USER)
    -- Player 4
    SetPlayerStartLocation(Player(4), 4)
    ForcePlayerStartLocation(Player(4), 4)
    SetPlayerColor(Player(4), ConvertPlayerColor(4))
    SetPlayerRacePreference(Player(4), RACE_PREF_HUMAN)
    SetPlayerRaceSelectable(Player(4), false)
    SetPlayerController(Player(4), MAP_CONTROL_USER)
    -- Player 5
    SetPlayerStartLocation(Player(5), 5)
    ForcePlayerStartLocation(Player(5), 5)
    SetPlayerColor(Player(5), ConvertPlayerColor(5))
    SetPlayerRacePreference(Player(5), RACE_PREF_HUMAN)
    SetPlayerRaceSelectable(Player(5), false)
    SetPlayerController(Player(5), MAP_CONTROL_USER)
    -- Player 6
    SetPlayerStartLocation(Player(6), 6)
    ForcePlayerStartLocation(Player(6), 6)
    SetPlayerColor(Player(6), ConvertPlayerColor(6))
    SetPlayerRacePreference(Player(6), RACE_PREF_HUMAN)
    SetPlayerRaceSelectable(Player(6), false)
    SetPlayerController(Player(6), MAP_CONTROL_USER)
    -- Player 7
    SetPlayerStartLocation(Player(7), 7)
    ForcePlayerStartLocation(Player(7), 7)
    SetPlayerColor(Player(7), ConvertPlayerColor(7))
    SetPlayerRacePreference(Player(7), RACE_PREF_HUMAN)
    SetPlayerRaceSelectable(Player(7), false)
    SetPlayerController(Player(7), MAP_CONTROL_USER)
    -- Player 8
    SetPlayerStartLocation(Player(8), 8)
    ForcePlayerStartLocation(Player(8), 8)
    SetPlayerColor(Player(8), ConvertPlayerColor(8))
    SetPlayerRacePreference(Player(8), RACE_PREF_HUMAN)
    SetPlayerRaceSelectable(Player(8), false)
    SetPlayerController(Player(8), MAP_CONTROL_USER)
    -- Player 9
    SetPlayerStartLocation(Player(9), 9)
    ForcePlayerStartLocation(Player(9), 9)
    SetPlayerColor(Player(9), ConvertPlayerColor(9))
    SetPlayerRacePreference(Player(9), RACE_PREF_HUMAN)
    SetPlayerRaceSelectable(Player(9), false)
    SetPlayerController(Player(9), MAP_CONTROL_USER)
    -- Player 10
    SetPlayerStartLocation(Player(10), 10)
    ForcePlayerStartLocation(Player(10), 10)
    SetPlayerColor(Player(10), ConvertPlayerColor(10))
    SetPlayerRacePreference(Player(10), RACE_PREF_HUMAN)
    SetPlayerRaceSelectable(Player(10), false)
    SetPlayerController(Player(10), MAP_CONTROL_USER)
    -- Player 11
    SetPlayerStartLocation(Player(11), 11)
    ForcePlayerStartLocation(Player(11), 11)
    SetPlayerColor(Player(11), ConvertPlayerColor(11))
    SetPlayerRacePreference(Player(11), RACE_PREF_HUMAN)
    SetPlayerRaceSelectable(Player(11), false)
    SetPlayerController(Player(11), MAP_CONTROL_USER)
    -- Player 12
    SetPlayerStartLocation(Player(12), 12)
    ForcePlayerStartLocation(Player(12), 12)
    SetPlayerColor(Player(12), ConvertPlayerColor(12))
    SetPlayerRacePreference(Player(12), RACE_PREF_HUMAN)
    SetPlayerRaceSelectable(Player(12), false)
    SetPlayerController(Player(12), MAP_CONTROL_USER)
    -- Player 13
    SetPlayerStartLocation(Player(13), 13)
    ForcePlayerStartLocation(Player(13), 13)
    SetPlayerColor(Player(13), ConvertPlayerColor(13))
    SetPlayerRacePreference(Player(13), RACE_PREF_HUMAN)
    SetPlayerRaceSelectable(Player(13), false)
    SetPlayerController(Player(13), MAP_CONTROL_USER)
    -- Player 14
    SetPlayerStartLocation(Player(14), 14)
    ForcePlayerStartLocation(Player(14), 14)
    SetPlayerColor(Player(14), ConvertPlayerColor(14))
    SetPlayerRacePreference(Player(14), RACE_PREF_HUMAN)
    SetPlayerRaceSelectable(Player(14), false)
    SetPlayerController(Player(14), MAP_CONTROL_USER)
    -- Player 15
    SetPlayerStartLocation(Player(15), 15)
    ForcePlayerStartLocation(Player(15), 15)
    SetPlayerColor(Player(15), ConvertPlayerColor(15))
    SetPlayerRacePreference(Player(15), RACE_PREF_HUMAN)
    SetPlayerRaceSelectable(Player(15), false)
    SetPlayerController(Player(15), MAP_CONTROL_USER)
    -- Player 16
    SetPlayerStartLocation(Player(16), 16)
    ForcePlayerStartLocation(Player(16), 16)
    SetPlayerColor(Player(16), ConvertPlayerColor(16))
    SetPlayerRacePreference(Player(16), RACE_PREF_HUMAN)
    SetPlayerRaceSelectable(Player(16), false)
    SetPlayerController(Player(16), MAP_CONTROL_USER)
    -- Player 17
    SetPlayerStartLocation(Player(17), 17)
    ForcePlayerStartLocation(Player(17), 17)
    SetPlayerColor(Player(17), ConvertPlayerColor(17))
    SetPlayerRacePreference(Player(17), RACE_PREF_HUMAN)
    SetPlayerRaceSelectable(Player(17), false)
    SetPlayerController(Player(17), MAP_CONTROL_USER)
    -- Player 18
    SetPlayerStartLocation(Player(18), 18)
    ForcePlayerStartLocation(Player(18), 18)
    SetPlayerColor(Player(18), ConvertPlayerColor(18))
    SetPlayerRacePreference(Player(18), RACE_PREF_HUMAN)
    SetPlayerRaceSelectable(Player(18), false)
    SetPlayerController(Player(18), MAP_CONTROL_USER)
    -- Player 19
    SetPlayerStartLocation(Player(19), 19)
    ForcePlayerStartLocation(Player(19), 19)
    SetPlayerColor(Player(19), ConvertPlayerColor(19))
    SetPlayerRacePreference(Player(19), RACE_PREF_HUMAN)
    SetPlayerRaceSelectable(Player(19), false)
    SetPlayerController(Player(19), MAP_CONTROL_USER)
    -- Player 20
    SetPlayerStartLocation(Player(20), 20)
    ForcePlayerStartLocation(Player(20), 20)
    SetPlayerColor(Player(20), ConvertPlayerColor(20))
    SetPlayerRacePreference(Player(20), RACE_PREF_HUMAN)
    SetPlayerRaceSelectable(Player(20), false)
    SetPlayerController(Player(20), MAP_CONTROL_USER)
    -- Player 21
    SetPlayerStartLocation(Player(21), 21)
    ForcePlayerStartLocation(Player(21), 21)
    SetPlayerColor(Player(21), ConvertPlayerColor(21))
    SetPlayerRacePreference(Player(21), RACE_PREF_HUMAN)
    SetPlayerRaceSelectable(Player(21), false)
    SetPlayerController(Player(21), MAP_CONTROL_USER)
    -- Player 22
    SetPlayerStartLocation(Player(22), 22)
    ForcePlayerStartLocation(Player(22), 22)
    SetPlayerColor(Player(22), ConvertPlayerColor(22))
    SetPlayerRacePreference(Player(22), RACE_PREF_HUMAN)
    SetPlayerRaceSelectable(Player(22), false)
    SetPlayerController(Player(22), MAP_CONTROL_USER)
    -- Player 23
    SetPlayerStartLocation(Player(23), 23)
    ForcePlayerStartLocation(Player(23), 23)
    SetPlayerColor(Player(23), ConvertPlayerColor(23))
    SetPlayerRacePreference(Player(23), RACE_PREF_HUMAN)
    SetPlayerRaceSelectable(Player(23), false)
    SetPlayerController(Player(23), MAP_CONTROL_USER)
end
function InitCustomTeams()
    -- Force: TRIGSTR_10956
    SetPlayerTeam(Player(0), 0)
    -- Force: TRIGSTR_10959
    SetPlayerTeam(Player(1), 1)
    SetPlayerTeam(Player(2), 1)
    SetPlayerTeam(Player(3), 1)
    SetPlayerTeam(Player(4), 1)
    SetPlayerTeam(Player(5), 1)
    SetPlayerTeam(Player(6), 1)
    SetPlayerTeam(Player(7), 1)
    SetPlayerTeam(Player(8), 1)
    SetPlayerTeam(Player(9), 1)
    SetPlayerTeam(Player(10), 1)
    SetPlayerTeam(Player(11), 1)
    SetPlayerTeam(Player(12), 1)
    -- Force: TRIGSTR_10960
    SetPlayerTeam(Player(13), 2)
    SetPlayerTeam(Player(14), 2)
    SetPlayerTeam(Player(15), 2)
    SetPlayerTeam(Player(16), 2)
    SetPlayerTeam(Player(17), 2)
    SetPlayerTeam(Player(18), 2)
    SetPlayerTeam(Player(19), 2)
    SetPlayerTeam(Player(20), 2)
    SetPlayerTeam(Player(21), 2)
    SetPlayerTeam(Player(22), 2)
    SetPlayerTeam(Player(23), 2)
end
function InitAllyPriorities()
    SetStartLocPrioCount(0, 1)
    SetStartLocPrio(0, 0, 2, MAP_LOC_PRIO_HIGH)
    SetStartLocPrioCount(1, 5)
    SetStartLocPrio(1, 0, 3, MAP_LOC_PRIO_LOW)
    SetStartLocPrio(1, 1, 8, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(1, 2, 10, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(1, 3, 11, MAP_LOC_PRIO_LOW)
    SetStartLocPrio(1, 4, 20, MAP_LOC_PRIO_HIGH)
    SetStartLocPrioCount(2, 2)
    SetStartLocPrio(2, 0, 0, MAP_LOC_PRIO_LOW)
    SetStartLocPrio(2, 1, 12, MAP_LOC_PRIO_HIGH)
    SetStartLocPrioCount(3, 3)
    SetStartLocPrio(3, 0, 8, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(3, 1, 9, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(3, 2, 20, MAP_LOC_PRIO_HIGH)
    SetStartLocPrioCount(4, 1)
    SetStartLocPrio(4, 0, 21, MAP_LOC_PRIO_HIGH)
    SetStartLocPrioCount(5, 4)
    SetStartLocPrio(5, 0, 0, MAP_LOC_PRIO_LOW)
    SetStartLocPrio(5, 1, 2, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(5, 2, 12, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(5, 3, 13, MAP_LOC_PRIO_HIGH)
    SetStartLocPrioCount(6, 2)
    SetStartLocPrio(6, 0, 15, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(6, 1, 17, MAP_LOC_PRIO_HIGH)
    SetStartLocPrioCount(7, 2)
    SetStartLocPrio(7, 0, 6, MAP_LOC_PRIO_LOW)
    SetStartLocPrio(7, 1, 15, MAP_LOC_PRIO_HIGH)
    SetStartLocPrioCount(8, 1)
    SetStartLocPrio(8, 0, 20, MAP_LOC_PRIO_HIGH)
    SetStartLocPrioCount(9, 1)
    SetStartLocPrio(9, 0, 3, MAP_LOC_PRIO_HIGH)
    SetStartLocPrioCount(10, 1)
    SetStartLocPrio(10, 0, 11, MAP_LOC_PRIO_HIGH)
    SetStartLocPrioCount(11, 2)
    SetStartLocPrio(11, 0, 10, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(11, 1, 14, MAP_LOC_PRIO_LOW)
    SetStartLocPrioCount(12, 1)
    SetStartLocPrio(12, 0, 2, MAP_LOC_PRIO_HIGH)
    SetStartLocPrioCount(13, 1)
    SetStartLocPrio(13, 0, 12, MAP_LOC_PRIO_HIGH)
    SetStartLocPrioCount(14, 1)
    SetStartLocPrio(14, 0, 11, MAP_LOC_PRIO_HIGH)
    SetStartLocPrioCount(15, 2)
    SetStartLocPrio(15, 0, 6, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(15, 1, 7, MAP_LOC_PRIO_HIGH)
    SetStartLocPrioCount(16, 1)
    SetStartLocPrio(16, 0, 19, MAP_LOC_PRIO_HIGH)
    SetStartLocPrioCount(17, 1)
    SetStartLocPrio(17, 0, 6, MAP_LOC_PRIO_HIGH)
    SetStartLocPrioCount(18, 1)
    SetStartLocPrio(18, 0, 23, MAP_LOC_PRIO_HIGH)
    SetStartLocPrioCount(19, 1)
    SetStartLocPrio(19, 0, 16, MAP_LOC_PRIO_HIGH)
    SetStartLocPrioCount(20, 1)
    SetStartLocPrio(20, 0, 8, MAP_LOC_PRIO_HIGH)
    SetStartLocPrioCount(21, 1)
    SetStartLocPrio(21, 0, 4, MAP_LOC_PRIO_HIGH)
    SetStartLocPrioCount(22, 2)
    SetStartLocPrio(22, 0, 4, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(22, 1, 21, MAP_LOC_PRIO_HIGH)
    SetStartLocPrioCount(23, 1)
    SetStartLocPrio(23, 0, 18, MAP_LOC_PRIO_HIGH)
end
--***************************************************************************
--*
--*  Main Initialization
--*
--***************************************************************************
