-- *  Cameras
-- 
-- ***************************************************************************
---@return nothing
function CreateCameras()
	
	gg_cam_Camera_001 = CreateCameraSetup()
	CameraSetupSetField(gg_cam_Camera_001, CAMERA_FIELD_ZOFFSET, 0.0, 0.0)
	CameraSetupSetField(gg_cam_Camera_001, CAMERA_FIELD_ROTATION, 89.0, 0.0)
	CameraSetupSetField(gg_cam_Camera_001, CAMERA_FIELD_ANGLE_OF_ATTACK, 310.9, 0.0)
	CameraSetupSetField(gg_cam_Camera_001, CAMERA_FIELD_TARGET_DISTANCE, 3980.0, 0.0)
	CameraSetupSetField(gg_cam_Camera_001, CAMERA_FIELD_ROLL, 0.0, 0.0)
	CameraSetupSetField(gg_cam_Camera_001, CAMERA_FIELD_FIELD_OF_VIEW, 70.0, 0.0)
	CameraSetupSetField(gg_cam_Camera_001, CAMERA_FIELD_FARZ, 5000.0, 0.0)
	CameraSetupSetField(gg_cam_Camera_001, CAMERA_FIELD_NEARZ, 16.0, 0.0)
	CameraSetupSetField(gg_cam_Camera_001, CAMERA_FIELD_LOCAL_PITCH, 0.0, 0.0)
	CameraSetupSetField(gg_cam_Camera_001, CAMERA_FIELD_LOCAL_YAW, 0.0, 0.0)
	CameraSetupSetField(gg_cam_Camera_001, CAMERA_FIELD_LOCAL_ROLL, 0.0, 0.0)
	CameraSetupSetDestPosition(gg_cam_Camera_001, -3864.1, 398.5, 0.0)
	
	gg_cam_HostRegion = CreateCameraSetup()
	CameraSetupSetField(gg_cam_HostRegion, CAMERA_FIELD_ZOFFSET, 0.0, 0.0)
	CameraSetupSetField(gg_cam_HostRegion, CAMERA_FIELD_ROTATION, 90.0, 0.0)
	CameraSetupSetField(gg_cam_HostRegion, CAMERA_FIELD_ANGLE_OF_ATTACK, 304.0, 0.0)
	CameraSetupSetField(gg_cam_HostRegion, CAMERA_FIELD_TARGET_DISTANCE, 1815.0, 0.0)
	CameraSetupSetField(gg_cam_HostRegion, CAMERA_FIELD_ROLL, 0.0, 0.0)
	CameraSetupSetField(gg_cam_HostRegion, CAMERA_FIELD_FIELD_OF_VIEW, 70.0, 0.0)
	CameraSetupSetField(gg_cam_HostRegion, CAMERA_FIELD_FARZ, 5000.0, 0.0)
	CameraSetupSetField(gg_cam_HostRegion, CAMERA_FIELD_NEARZ, 16.0, 0.0)
	CameraSetupSetField(gg_cam_HostRegion, CAMERA_FIELD_LOCAL_PITCH, 0.0, 0.0)
	CameraSetupSetField(gg_cam_HostRegion, CAMERA_FIELD_LOCAL_YAW, 0.0, 0.0)
	CameraSetupSetField(gg_cam_HostRegion, CAMERA_FIELD_LOCAL_ROLL, 0.0, 0.0)
	CameraSetupSetDestPosition(gg_cam_HostRegion, -25414.8, 29492.4, 0.0)
	
	gg_cam_GW2 = CreateCameraSetup()
	CameraSetupSetField(gg_cam_GW2, CAMERA_FIELD_ZOFFSET, 0.0, 0.0)
	CameraSetupSetField(gg_cam_GW2, CAMERA_FIELD_ROTATION, 78.0, 0.0)
	CameraSetupSetField(gg_cam_GW2, CAMERA_FIELD_ANGLE_OF_ATTACK, 319.6, 0.0)
	CameraSetupSetField(gg_cam_GW2, CAMERA_FIELD_TARGET_DISTANCE, 1650.0, 0.0)
	CameraSetupSetField(gg_cam_GW2, CAMERA_FIELD_ROLL, 0.0, 0.0)
	CameraSetupSetField(gg_cam_GW2, CAMERA_FIELD_FIELD_OF_VIEW, 70.0, 0.0)
	CameraSetupSetField(gg_cam_GW2, CAMERA_FIELD_FARZ, 10000.0, 0.0)
	CameraSetupSetField(gg_cam_GW2, CAMERA_FIELD_NEARZ, 16.0, 0.0)
	CameraSetupSetField(gg_cam_GW2, CAMERA_FIELD_LOCAL_PITCH, 0.0, 0.0)
	CameraSetupSetField(gg_cam_GW2, CAMERA_FIELD_LOCAL_YAW, 0.0, 0.0)
	CameraSetupSetField(gg_cam_GW2, CAMERA_FIELD_LOCAL_ROLL, 0.0, 0.0)
	CameraSetupSetDestPosition(gg_cam_GW2, 1560.8, 8794.1, 0.0)
	
	gg_cam_GW3 = CreateCameraSetup()
	CameraSetupSetField(gg_cam_GW3, CAMERA_FIELD_ZOFFSET, 0.0, 0.0)
	CameraSetupSetField(gg_cam_GW3, CAMERA_FIELD_ROTATION, 320.2, 0.0)
	CameraSetupSetField(gg_cam_GW3, CAMERA_FIELD_ANGLE_OF_ATTACK, 323.0, 0.0)
	CameraSetupSetField(gg_cam_GW3, CAMERA_FIELD_TARGET_DISTANCE, 1500.0, 0.0)
	CameraSetupSetField(gg_cam_GW3, CAMERA_FIELD_ROLL, 0.0, 0.0)
	CameraSetupSetField(gg_cam_GW3, CAMERA_FIELD_FIELD_OF_VIEW, 70.0, 0.0)
	CameraSetupSetField(gg_cam_GW3, CAMERA_FIELD_FARZ, 10000.0, 0.0)
	CameraSetupSetField(gg_cam_GW3, CAMERA_FIELD_NEARZ, 16.0, 0.0)
	CameraSetupSetField(gg_cam_GW3, CAMERA_FIELD_LOCAL_PITCH, 0.0, 0.0)
	CameraSetupSetField(gg_cam_GW3, CAMERA_FIELD_LOCAL_YAW, 0.0, 0.0)
	CameraSetupSetField(gg_cam_GW3, CAMERA_FIELD_LOCAL_ROLL, 0.0, 0.0)
	CameraSetupSetDestPosition(gg_cam_GW3, 24702.7, 27168.4, 0.0)
	
	gg_cam_GW4 = CreateCameraSetup()
	CameraSetupSetField(gg_cam_GW4, CAMERA_FIELD_ZOFFSET, 0.0, 0.0)
	CameraSetupSetField(gg_cam_GW4, CAMERA_FIELD_ROTATION, 55.2, 0.0)
	CameraSetupSetField(gg_cam_GW4, CAMERA_FIELD_ANGLE_OF_ATTACK, 326.9, 0.0)
	CameraSetupSetField(gg_cam_GW4, CAMERA_FIELD_TARGET_DISTANCE, 1815.0, 0.0)
	CameraSetupSetField(gg_cam_GW4, CAMERA_FIELD_ROLL, 0.0, 0.0)
	CameraSetupSetField(gg_cam_GW4, CAMERA_FIELD_FIELD_OF_VIEW, 70.0, 0.0)
	CameraSetupSetField(gg_cam_GW4, CAMERA_FIELD_FARZ, 10000.0, 0.0)
	CameraSetupSetField(gg_cam_GW4, CAMERA_FIELD_NEARZ, 16.0, 0.0)
	CameraSetupSetField(gg_cam_GW4, CAMERA_FIELD_LOCAL_PITCH, 0.0, 0.0)
	CameraSetupSetField(gg_cam_GW4, CAMERA_FIELD_LOCAL_YAW, 0.0, 0.0)
	CameraSetupSetField(gg_cam_GW4, CAMERA_FIELD_LOCAL_ROLL, 0.0, 0.0)
	CameraSetupSetDestPosition(gg_cam_GW4, -21409.7, 16525.6, 0.0)
	
	gg_cam_GW5 = CreateCameraSetup()
	CameraSetupSetField(gg_cam_GW5, CAMERA_FIELD_ZOFFSET, 0.0, 0.0)
	CameraSetupSetField(gg_cam_GW5, CAMERA_FIELD_ROTATION, 32.7, 0.0)
	CameraSetupSetField(gg_cam_GW5, CAMERA_FIELD_ANGLE_OF_ATTACK, 327.1, 0.0)
	CameraSetupSetField(gg_cam_GW5, CAMERA_FIELD_TARGET_DISTANCE, 1815.0, 0.0)
	CameraSetupSetField(gg_cam_GW5, CAMERA_FIELD_ROLL, 0.0, 0.0)
	CameraSetupSetField(gg_cam_GW5, CAMERA_FIELD_FIELD_OF_VIEW, 70.0, 0.0)
	CameraSetupSetField(gg_cam_GW5, CAMERA_FIELD_FARZ, 10000.0, 0.0)
	CameraSetupSetField(gg_cam_GW5, CAMERA_FIELD_NEARZ, 16.0, 0.0)
	CameraSetupSetField(gg_cam_GW5, CAMERA_FIELD_LOCAL_PITCH, 0.0, 0.0)
	CameraSetupSetField(gg_cam_GW5, CAMERA_FIELD_LOCAL_YAW, 0.0, 0.0)
	CameraSetupSetField(gg_cam_GW5, CAMERA_FIELD_LOCAL_ROLL, 0.0, 0.0)
	CameraSetupSetDestPosition(gg_cam_GW5, 16091.5, -16556.1, 0.0)
	
	gg_cam_GW1 = CreateCameraSetup()
	CameraSetupSetField(gg_cam_GW1, CAMERA_FIELD_ZOFFSET, 0.0, 0.0)
	CameraSetupSetField(gg_cam_GW1, CAMERA_FIELD_ROTATION, 130.3, 0.0)
	CameraSetupSetField(gg_cam_GW1, CAMERA_FIELD_ANGLE_OF_ATTACK, 325.6, 0.0)
	CameraSetupSetField(gg_cam_GW1, CAMERA_FIELD_TARGET_DISTANCE, 1996.5, 0.0)
	CameraSetupSetField(gg_cam_GW1, CAMERA_FIELD_ROLL, 0.0, 0.0)
	CameraSetupSetField(gg_cam_GW1, CAMERA_FIELD_FIELD_OF_VIEW, 70.0, 0.0)
	CameraSetupSetField(gg_cam_GW1, CAMERA_FIELD_FARZ, 10000.0, 0.0)
	CameraSetupSetField(gg_cam_GW1, CAMERA_FIELD_NEARZ, 16.0, 0.0)
	CameraSetupSetField(gg_cam_GW1, CAMERA_FIELD_LOCAL_PITCH, 0.0, 0.0)
	CameraSetupSetField(gg_cam_GW1, CAMERA_FIELD_LOCAL_YAW, 0.0, 0.0)
	CameraSetupSetField(gg_cam_GW1, CAMERA_FIELD_LOCAL_ROLL, 0.0, 0.0)
	CameraSetupSetDestPosition(gg_cam_GW1, -2593.3, 27837.7, 0.0)
	
end
-- ***************************************************************************
-- 
